name: UniversityProjectSemester6
services:
  toDoApi:
    image: minimalwebapi_net9
    build:
      context: ./MinimalWebApi_net9
      dockerfile: Dockerfile
  toDoDb:
    image: mcr.microsoft.com/mssql/server
volumes:
  minnimawebapi_mssql_order:
    external: true
    
